### ISSUE TITLE
include_vinyl_count should be false by default

### ISSUE THREAD

**Issue by bofm** [tarantool/stat#22]
`include_vinyl_count` option should be `false` by default because it hits performance and causes latency spikes when spaces contain much data.

Moreover, people who have been using `stat` package for monitoring purposes may get latency problems after upgrading `stat` to the recent version from the old one.

**Comment by Totktonada** [comment]
The module is [deprecated](https://github.com/tarantool/stat/commit/9b39a075ef59bc52754486511cb8cb44e46540f5) in favor of [metrics](https://github.com/tarantool/metrics). I'll close the issue.

If you still have related problems around default metrics in the metrics module, let us know: file an issue to metrics or reach us in the Telegram [chat](https://t.me/tarantool) (the Russian speaking chat is [here](https://t.me/tarantoolru)).

However, just like here, it is possible that some proposals may be rejected due to backward compatibility. Anyway, such problem still may be resolved via proper documenting of potential pitfalls.
